### ISSUE TITLE
Subcommand 'profile' asking for cutoffs arguments

### ISSUE THREAD

**Issue by metaganal** [zellerlab/cayman#12]
I tried running cayman v0.10.0 with `cayman profile`, but it raises this error:
```AttributeError: 'Namespace' object has no attribute 'cutoffs'```

Looking at the `__main__.py`, it looks like this is due to the if-clause in line 27-28.
Is the cutoff parameter also essential for the profile subcommand or is it a broken if-clause specific to annotate_proteome?

Another question, it looks like the default db_format was changed from bed format to HMMER format (`handle_args.py` line 80-86). Was it changed to make it accept the [Zenodo annotations](https://zenodo.org/records/10473258) by default?

**Comment by metaganal** [comment]
@cschu Thanks for the quick reply.

Here is the command line call I used that resulted in the error.
```
cayman profile -1 "$ID"_R1.fastq.gz -2 "$ID"_R2.fastq.gz \
--cpus_for_alignment 8 \
--out_prefix "$outdir"/"$ID"_ \
"$dbdir"/annots/GMGC10.human-gut.95nr.no-rare.0.5.percent.prevalence_all_v3_FINAL.csv \
"$dbdir"/bwa_index/human
```

The BWA index was prepared from `GMGC10.human-gut.95nr.0.5.percent.prevalence.fna.gz`, with this parameter:
`bwa index -p cayman_human -b 20000000000 "$refpath"`.
I'm running it within a Singularity container, built with the Remote Builder based on the latest definition file.

P.S. Thanks for the detailed explanation on the format change. As a user, I was somewhat confused as the Zenodo annotations was not in the 4-column format described in the documentation.

**Comment by cschu** [comment]
Hi @metaganal ,

Thanks for reporting this. That was an oversight when adding the `annotate_proteome` mode. Indeed, the `cutoffs` parameter is not required for the `profile` mode and the check was misplaced.

I fixed this and there is now a version 0.10.1.

Please let me know if this is working on your side.

Best,
Christian

**Comment by metaganal** [comment]
@cschu Thanks for the quick fix. It ran smoothly after updating to v0.10.1.

**Comment by cschu** [comment]
Perfect, glad to hear that.

Best,
Christian
